services:
  api:
    container_name: apiLoans
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - pg
    command: bash -c 'yarn migration:generate ./src/migrations/initialCommit && yarn migration:run && yarn dev'
  pg:
    container_name: loansDb
    image: postgres
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - 5432:5432
